export default PermissionsData = [
  {
    name: "MyFinances view",
    content: "MyFinances view",
    expect_text1: "my_finance.view",
    expect_text2: "my_finance.edit",
    expect_text3: "contacts.view",
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
  },
  {
    name: "MyFinance edit",
    element: "#menu- > .MuiPaper-root > .MuiList-root > [tabindex='0']",
    content: "MyFinance edit",
    expect_text1: "my_finance.view",
    expect_text2: "my_finance.edit",
    expect_text3: "contacts.view",
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
  },
  {
    name: "MyFinance edit/add",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(2)",
    content: "MyFinance edit/add",
    expect_text1: "my_finance.view",
    expect_text2: "my_finance.edit",
    expect_text3: "my_finance.add",
    expect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
  },
  {
    name: "MyFinance edit/delete",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(3)",
    content: "MyFinance edit/delete",
    expect_text1: "my_finance.view",
    expect_text2: "my_finance.edit",
    expect_text3: "my_finance.delete",
    expect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
  },
  {
    name: "MyFinance full with property",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(4)",
    content: "MyFinance full with property",
    expect_text1: "my_finance.view",
    expect_text2: "my_finance.edit",
    expect_text3: "my_finance.delete",
    expect_text4: "contacts.view",
    expect_text5: "my_finance.add",
    expect_text6: "property.view",
  },
  {
    name: "Property view",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(5)",
    content: "Property view",
    expect_text1: "property.view",
    expect_text2: null,
    expect_text3: null,
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
  },
  {
    name: "Property edit",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(6)",
    contnet: "Property edit",
    expect_text1: "property.view",
    expect_text2: "property.edit",
    expect_text3: "contacts.view",
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
  },
  {
    name: "Property edit/add",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(7)",
    content: "Property edit/add",
    expect_text1: "property.view",
    expect_text2: "property.edit",
    expect_text3: "property.add",
    expect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
  },
  {
    name: "Property edit/delete",
    element: ".MuiList-root > :nth-child(8)",
    content: "Property edit/delete",
    expect_text1: "property.view",
    expect_text2: "property.edit",
    expect_text3: "property.delete",
    epxect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
  },
  {
    name: "Property full",
    element: ".MuiList-root > :nth-child(8)",
  },
];
