export const PermissionsData = [
  {
    permission: "MyFinances view",
    content: "MyFinances view",
    expect_text1: "my_finance.view",
    expect_text2: "my_finance.edit",
    expect_text3: "contacts.view",
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "MyFinance edit",
    element: "#menu- > .MuiPaper-root > .MuiList-root > [tabindex='0']",
    content: "MyFinance edit",
    expect_text1: "my_finance.view",
    expect_text2: "my_finance.edit",
    expect_text3: "contacts.view",
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "MyFinance edit/add",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(2)",
    content: "MyFinance edit/add",
    expect_text1: "my_finance.view",
    expect_text2: "my_finance.edit",
    expect_text3: "my_finance.add",
    expect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "MyFinance edit/delete",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(3)",
    content: "MyFinance edit/delete",
    expect_text1: "my_finance.view",
    expect_text2: "my_finance.edit",
    expect_text3: "my_finance.delete",
    expect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "MyFinance full with property",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(4)",
    content: "MyFinance full with property",
    expect_text1: "my_finance.view",
    expect_text2: "my_finance.edit",
    expect_text3: "my_finance.delete",
    expect_text4: "contacts.view",
    expect_text5: "my_finance.add",
    expect_text6: "property.view",
  },
  {
    permission: "Property view",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(5)",
    content: "Property view",
    expect_text1: "property.view",
    expect_text2: null,
    expect_text3: null,
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "Property edit",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(6)",
    contnet: "Property edit",
    expect_text1: "property.view",
    expect_text2: "property.edit",
    expect_text3: "contacts.view",
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
  },
  {
    permission: "Property edit/add",
    element: "#menu- > .MuiPaper-root > .MuiList-root > :nth-child(7)",
    content: "Property edit/add",
    expect_text1: "property.view",
    expect_text2: "property.edit",
    expect_text3: "property.add",
    expect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "Property edit/delete",
    element: ".MuiList-root > :nth-child(8)",
    content: "Property edit/delete",
    expect_text1: "property.view",
    expect_text2: "property.edit",
    expect_text3: "property.delete",
    epxect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "Property full",
    element: ".MuiList-root > :nth-child(9)",
    content: "Property full",
    expect_text1: "property.add",
    expect_text2: "property.delete",
    expect_text3: "property.edit",
    expect_text4: "property.view",
    expect_text5: "contacts.view",
    expect_text6: null,
  },
  {
    permission: "MyCollectables view",
    element: ".MuiList-root > :nth-child(10)",
    content: "MyCollectables view",
    expect_text1: "my_collectables.view",
  },
  {
    permission: "MyCollectables edit",
    element: ".MuiList-root > :nth-child(11)",
    content: "MyCollectables edit",
    expect_text1: "my_collectables.view",
    expect_text2: "my_collectables.edit",
    expect_text3: "contacts.view",
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "MyCollectables edit/add",
    element: ".MuiList-root > :nth-child(12)",
    content: "MyCollectables edit/add",
    expect_text1: "my_collectables.view",
    expect_text2: "my_collectables.edit",
    expect_text3: "my_collectables.add",
    expect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "MyCollectables edit/delete",
    element: ".MuiList-root > :nth-child(13)",
    content: "MyCollectables edit/delete",
    expect_text1: "my_collectables.view",
    expect_text2: "my_collectables.edit",
    expect_text3: "my_collectables.delete",
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "MyCollectables full with property",
    element: ".MuiList-root > :nth-child(14)",
    content: "MyCollectables full with property",
    expect_text1: "my_collectables.add",
    expect_text2: "my_collectables.delete",
    expect_text3: "my_collectables.edit",
    expect_text4: "my_collectables.view",
    expect_text5: "contacts.view",
    expect_text6: "property.view",
  },
  {
    permission: "MyBelongings view",
    element: ".MuiList-root > :nth-child(15)",
    content: "MyBelongings view",
    expect_text1: "belongings.view",
    expect_text2: null,
    expect_text3: null,
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "MyBelongings edit",
    element: ".MuiList-root > :nth-child(16)",
    content: "MyBelongings edit",
    expect_text1: "belongings.view",
    expect_text2: "belongings.edit",
    expect_text3: "contacts.view",
    expect_text4: null,
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "MyBelongings edit/add",
    element: ".MuiList-root > :nth-child(17)",
    content: "MyBelongings edit/add",
    expect_text1: "belongings.view",
    expect_text2: "belongings.edit",
    expect_text3: "belongings.add",
    expect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "MyBelongings edit/delete",
    element: ".MuiList-root :nth-child(18)",
    content: "MyBelongings edit/delete",
    expect_text1: "belongings.view",
    expect_text2: "belongings.edit",
    expect_text3: "belongings.delete",
    expect_text4: "contacts.view",
    expect_text5: null,
    expect_text6: null,
    expect_text7: null,
    expect_text8: null,
    expect_text9: null,
  },
  {
    permission: "Viewer",
    element: ".MuiList-root > :nth-child(19)",
    content: "Viewer",
    expect_text1: "portfolio.view",
    expect_text2: "cash_account.view",
    expect_text3: "insurance.view",
    expect_text4: "crypto.view",
    expect_text5: "other_investments.view",
    expect_text6: "belongings.view",
    expect_text7: "groups.view",
    expect_text8: "valut.view",
    expect_text9: "delegates.view",
  },
];
